#!/bin/sh

case "$1" in
	start)
 ### remember to use nohup "&" etc. to start as daemon is services don't do itself
        ### example
        ### HEREAFTER 3 modes to start of  apache2 in the chroot env.
        # chroot $DEB_BASE /bin/bash -c "/etc/init.d/apache2 start"
        # chroot $DEB_BASE /etc/init.d/apache2 start
        # /usr/bin/deb_bash /etc/init.d/apache2 start
        ### using another user than root / admin
        ### HERAFTER start of vncserver under qnap user
        # chroot $DEB_BASE /bin/bash -c "su -c \"vncserver -geometry 1152x864\" - qnap"
        ### connect to a user
        # /usr/bin/deb_bash su - qnap
        echo " start services"
	;;
	stop)
 ### remember to kill or stop daemon
        # be attention for ex. to dbus if you run X11 environment
        # you need in this case to add
        # chroot $DEB_BASE /bin/bash -c "/etc/init.d/dbus stop"
        # or you can't umount /dev for ex.
        echo " stop services"
	;;
	*)
	echo " usage : $0 start|stop "
	exit 1
esac
exit 0

