#!/bin/sh

make_base(){
	# Determine BASE installation location according to /etc/config/def_share.info
	VOL_BASE=`/sbin/getcfg SHARE_DEF defVolMP -d "" -f /etc/config/def_share.info`
	if [ -z $VOL_BASE ] ; then
		echo "The Public share not found."
		return 1
	fi
}

## Main
if [ -z $1 ] ; then
	echo " Please enter service_name to remove "
	echo " Usage : deb_remove_serv service_name [-v version]"
	exit 1
fi

make_base
QPKG_DIR=$VOL_BASE/.qpkg/debian6
## installation inside debian chroot

## get VERSION
VERSION=`/sbin/getcfg debian6 CURRENT_VERSION -d "" -f /etc/config/debian6.conf`
if [ "$2" = "-v" ] ; then
	if [ -n "$3" ] ; then
		VERSION=$3
	else
		echo " -v need a chroot version after "
	fi
fi
## get DEB_BASE
DEB_BASE=`/sbin/getcfg $VERSION DEB_BASE -d "" -f /etc/config/debian6.conf`
if [ -z $DEB_BASE ] ; then
	echo " hum Debian BASE is not defined ??? debian chroot MUST be up "
	exit 1
fi

## verify that $1 service exist ....
ENABLE=`/sbin/getcfg $VERSION ${1}_ENABLE -d "" -f /etc/config/debian6.conf`
if [ -z $ENABLE ] ; then
	echo "hum seems that the service $1 don't exist in $VERSION env."
	exit 1
fi
## force stop
echo " stop service $1 "
/bin_deb/deb_run_serv $1 stop -v $VERSION
##
/bin/sleep 1
/bin/sync
##
## remove service from current version
/sbin/setcfg -e $VERSION $1_ENABLE -f /etc/config/debian6.conf
/sbin/setcfg -e $VERSION $1 -f /etc/config/debian6.conf
##
rm -f $QPKG_DIR/services/${VERSION}/*$1


exit 0
