#!/bin/sh

make_base(){
# Determine BASE installation location according to smb.conf
BASE_GROUP="/share/HDA_DATA /share/HDB_DATA /share/HDC_DATA /share/HDD_DATA /share/HDE_DATA /share/HDF_DATA /share/HDG_DATA /share/HDH_DATA /share/MD0_DATA /share/MD1_DATA /share/MD2_DATA /share/MD3_DATA"
publicdir=`/sbin/getcfg Public path -f /etc/config/smb.conf`
if [ ! -z $publicdir ] && [ -d $publicdir ];then
        publicdirp1=`/bin/echo $publicdir | /bin/cut -d "/" -f 2`
        publicdirp2=`/bin/echo $publicdir | /bin/cut -d "/" -f 3`
        publicdirp3=`/bin/echo $publicdir | /bin/cut -d "/" -f 4`
        if [ ! -z $publicdirp1 ] && [ ! -z $publicdirp2 ] && [ ! -z $publicdirp3 ]; then
                [ -d "/${publicdirp1}/${publicdirp2}/Public" ] && VOL_BASE="/${publicdirp1}/${publicdirp2}"
        fi
fi

# Determine BASE installation location by checking where the Public folder is.
if [ -z $VOL_BASE ]; then
        for datadirtest in $BASE_GROUP; do
                [ -d $datadirtest/Public ] && VOL_BASE="/${publicdirp1}/${publicdirp2}"
        done
fi
if [ -z $VOL_BASE ] ; then
        echo "The Public share not found."
        return 1
fi

}

## Main
if [ -z $1 ] ; then
	echo " Please enter service_name to remove "
	echo " Usage : deb_remove_serv service_name [-v version]"
	exit 1
fi

make_base
QPKG_DIR=$VOL_BASE/.qpkg/debian6
## installation inside debian chroot

## get VERSION
VERSION=`/sbin/getcfg debian6 CURRENT_VERSION -d "" -f /etc/config/debian6.conf`
if [ "$2" = "-v" ] ; then
	if [ -n "$3" ] ; then
		VERSION=$3
	else
		echo " -v need a chroot version after "
	fi
fi
## get DEB_BASE
DEB_BASE=`/sbin/getcfg $VERSION DEB_BASE -d "" -f /etc/config/debian6.conf`
if [ -z $DEB_BASE ] ; then
	echo " hum Debian BASE is not defined ??? debian chroot MUST be up "
	exit 1
fi

## verify that $1 service exist ....
ENABLE=`/sbin/getcfg $VERSION ${1}_ENABLE -d "" -f /etc/config/debian6.conf`
if [ -z $ENABLE ] ; then
	echo "hum seems that the service $1 don't exist in $VERSION env."
	exit 1
fi
## force stop
echo " stop service $1 "
/bin_deb/deb_run_serv $1 stop -v $VERSION
##
/bin/sleep 1
/bin/sync
##
## remove service from current version
/sbin/setcfg -e $VERSION $1_ENABLE -f /etc/config/debian6.conf
/sbin/setcfg -e $VERSION $1 -f /etc/config/debian6.conf
##
rm -f $QPKG_DIR/services/${VERSION}/*$1


exit 0
